### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by xujinchang** [nilboy/pixel-recursive-super-resolution#1]
Hi, when i ran the scripts, i got the following error,
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    tf.app.run()
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 22, in main
    solver = Solver()
  File "/local/home/share/xujinchang/project/learn_pytorch/pixel-recursive-super-resolution-master/solver.py", line 38, in __init__
    self.net = Net(self.dataset.hr_images, self.dataset.lr_images, 'prsr')
  File "/local/home/share/xujinchang/project/learn_pytorch/pixel-recursive-super-resolution-master/net.py", line 18, in __init__
    self.construct_net(hr_images, lr_images)
  File "/local/home/share/xujinchang/project/learn_pytorch/pixel-recursive-super-resolution-master/net.py", line 82, in construct_net
    self.prior_logits = self.prior_network(hr_images)
  File "/local/home/share/xujinchang/project/learn_pytorch/pixel-recursive-super-resolution-master/net.py", line 39, in prior_network
    prior_logits = tf.concat([prior_logists0,prior_logists1,prior_logists2],3)
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 865, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 662, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/software/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
by the way, my tensorflow version is 0.11.0rc0.
Thanks a lot.

**Comment by nilboy** [comment]
tf.concat api has changed from tf-1.0. you can refer to http://stackoverflow.com/questions/41813665/tensorflow-slim-typeerror-expected-int32-got-list-containing-tensors-of-type

**Comment by xujinchang** [comment]
@nilboy thanks a lot. I have solved these problems. I have modified all the different api in the codes manually according to https://www.tensorflow.org/install/migration. Now, it can run successfully.

**Comment by luckyboysmith** [comment]
@xujinchang   can u share your code after modified?thanks a lot
