### ISSUE TITLE
InvalidArgumentError (see above for traceback): Invalid JPEG data, size 1179648

### ISSUE THREAD

**Issue by luckyboysmith** [nilboy/pixel-recursive-super-resolution#8]
再次打扰 程序运行中出现了错误 尝试了百度 无果 希望能得到您的帮助
E tensorflow/core/lib/jpeg/jpeg_mem.cc:221] Premature end of JPEG data. Stopped at line 3262/4256
step 4230, loss = 8.41 (20.3 examples/sec; 1.574 sec/batch)
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tools/train.py", line 23, in main
    solver.train()
  File "/home/wangkun/prsr/solver.py", line 88, in train
    coord.join(threads)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data, size 1179648
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, 

try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ReaderRead:1)]]
	 [[Node: ResizeBilinear_1/_15 = _Recv[client_terminated=false, 

recv_device="/job:localhost/replica:0/task:0/gpu:7", send_device="/job:localhost/replica:0/task:0/cpu:0", 

send_device_incarnation=1, tensor_name="edge_10_ResizeBilinear_1", tensor_type=DT_FLOAT, 

_device="/job:localhost/replica:0/task:0/gpu:7"]()]]

Caused by op u'DecodeJpeg', defined at:
  File "tools/train.py", line 26, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tools/train.py", line 22, in main
    solver = Solver()
  File "/home/wangkun/prsr/solver.py", line 36, in __init__
    self.dataset = DataSet(conf.imgs_list_path, self.num_epoch, self.batch_size)
  File "/home/wangkun/prsr/data.py", line 18, in __init__
    image = tf.image.decode_jpeg(image_file, 3)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 311, in decode_jpeg
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 1179648
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, 

try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ReaderRead:1)]]
	 [[Node: ResizeBilinear_1/_15 = _Recv[client_terminated=false, 

recv_device="/job:localhost/replica:0/task:0/gpu:7", send_device="/job:localhost/replica:0/task:0/cpu:0", 

send_device_incarnation=1, tensor_name="edge_10_ResizeBilinear_1", tensor_type=DT_FLOAT, 

_device="/job:localhost/replica:0/task:0/gpu:7"]()]]

**Comment by luckyboysmith** [comment]
虽然自己尝试做了一些处理，所谓的处理就是 将size大的图片给剔除了
可是，出现这个问题的原因是硬件不行的原因吗？
谢谢！！！！！！！！

**Comment by nilboy** [comment]
可能是吧。。。

**Comment by luckyboysmith** [comment]
非常感谢你的帮助！
